### ISSUE TITLE
Make the use of environment variables for handler more like core k8s

### ISSUE THREAD

**Issue by trisberg** [projectriff/cli#39]
In the k8s PodSpec there are two ways of setting the env vars `env` and `envFrom`. The latter is used like this:

```
      envFrom:
      - secretRef:
           name: my-secret
         prefix: mydb
```

and this results in all keys in the configMap/secret being added to the environment with the provided prefix if that was specified. See [Configure all key-value pairs in a Secret as container environment variables](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables).

We don't have a way of supporting this right now. We should adjust our `--env` and `--envFrom` support to better match this. 

### Suggestion:

- Keep what we have for `--env`

    example:	  

    `--env MY_VAR=my-value`

    results in:

    ```
    - env:
      - name: MY_VAR
        value: my-value
    ```

- Change `--env-from` to be `--env-value-from`

    examples:

    `--env-value-from MY_SECRET_VALUE=secretKeyRef:my-secret-name:key-in-secret`

    results in:
    ```	
    - env:
      - name: MY_SECRET_VALUE
        valueFrom:
          secretKeyRef:
            key: key-in-secret
            name: my-secret-name
    ```

    `--env-value-from MY_CONFIG_MAP_VALUE=configMapKeyRef:my-config-map-name:key-in-config-map`

    results in:
    ```	
    - env:
      - name: MY_CONFIG_MAP_VALUE
        valueFrom:
          configMapKeyRef:
            key: key-in-config-map
            name: my-config-map-name
    ```

- Add support for `envFrom` by adding a `--env-from-source` flag

    examples:	  

    `--env-from-source configMapRef:my-config-map-name`

    results in:
    ```	
    - envFrom:
      - configMapRef:
          name: my-config-map-name
    ```

    `--env-from-source prefix_:secretRef:my-secret-name`

    results in:
    ```	
    - envFrom:
      - prefix: prefix_
        secretRef:
          name: my-secret-name
    ```

**Comment by trisberg** [comment]
There is an alternative suggestion from @markfisher 

### Suggestion:

- Keep what we have for `--env`

    example:	  

    `--env MY_VAR=my-value`

    results in:

    ```
    - env:
      - name: MY_VAR
        value: my-value
    ```

- Change `--env-from` to accept `secretKeyRef` and  `configMapKeyRef` as well as `secretRef` and `configMapRef`

    examples:

    `--env-from MY_SECRET_VALUE=secretKeyRef:my-secret-name:key-in-secret`

    results in:
    ```	
    - env:
      - name: MY_SECRET_VALUE
        valueFrom:
          secretKeyRef:
            key: key-in-secret
            name: my-secret-name
    ```


    `--env-from MY_CONFIG_MAP_VALUE=configMapKeyRef:my-config-map-name:key-in-config-map`

    results in:
    ```	
    - env:
      - name: MY_CONFIG_MAP_VALUE
        valueFrom:
          configMapKeyRef:
            key: key-in-config-map
            name: my-config-map-name
    ```


    `--env-from configMapRef:my-config-map-name`

    results in:
    ```	
    - envFrom:
      - configMapRef:
          name: my-config-map-name
    ```


    `--env-from prefix_:secretRef:my-secret-name`

    results in:
    ```	
    - envFrom:
      - prefix: prefix_
        secretRef:
          name: my-secret-name
    ```
