### ISSUE TITLE
Enable CLI to define a volume mount for secrets/configMaps

### ISSUE THREAD

**Issue by trisberg** [projectriff/cli#57]
We should make it possible to mount a secret or a configMap as a volumeMount for a function/app container. It should also be possible to define the mountPath and file path for the secret/configMap item.

I suggest the following syntax:
`--volume-mount name:/mountPath/itemPath={secretRef|configMapRef}:resource:key`

Example: 

```
--volume-mount config:/config/application-refresh.yaml=secretRef:mypets-refresh:application.yaml
```

should result in:

```
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: mypets-refresh
          items:
          - key: application.yaml
            path: application-refresh.yaml
```
