### ISSUE TITLE
Change --env-from to be --env-value-from

### ISSUE THREAD

**Issue by trisberg** [projectriff/cli#70]
If we change `--env-from` to be `--env-value-from` then this would better match the Kubernetes API:

```
- env:
  - name: MY_SECRET_VALUE
    valueFrom:
      secretKeyRef:
        key: key-in-secret
        name: my-secret-name
```

This is part of the suggested changes in https://github.com/projectriff/cli/issues/39
